### ISSUE TITLE
the cache encoding is not consistent

### ISSUE THREAD

**Issue by yupbank** [fengsp/rc#2]
hey i was using this lib, as my result is being encoded by some internal utf8?

so every time the encoding differs as i get from cache or from my own function 

normally the first time i will fail :(

**Comment by fengsp** [comment]
I don't get it, can you add some code examples?

**Comment by yupbank** [comment]
i think it is more or less like below..
and i have added a pull request to fix this :) 

```
from rc import Cache
mycache = Cache()

@mycache.cache()
def x(a):
     return  a.encode('u8')

def test_encoding_consistancy():
      s_one =x('a')
      s_two = x('a')
     assert isinstance(s_one, unicode) ==  isinstance(s_two, unicode) 


if __name__ == "__main__":
    test_encoding_consistancy()

```

**Comment by fengsp** [comment]
@yupbank By default, we use `JSONSerializer`, which return unicode.  If caching bytes is what you want, you can do that easily by write your own serializer, it can be one serializer that doesn't serialize at all.  For more details, see http://rc.readthedocs.org/en/latest/serializer.html#json-serializer

**Comment by yupbank** [comment]
my point is the consistency..

**Comment by fengsp** [comment]
Sorry but the `json` module doesn't have the consistency :(  
Any good ideas on one serializer that is consistent?

**Comment by yupbank** [comment]
you can check my pull request :)

it's a bit hack to force the result of cache into only one encoding type :)

**Comment by fengsp** [comment]
@yupbank What if I return one dict of `str` ?    :)

**Comment by yupbank** [comment]
hmm.. do not really understand your point..

by consistent, i mean, the return value of a cached function should be at
least the same every time i called.

to make it more gracefully, it should reserve the encoding as to the
returning value of what exactly been returned.

**Comment by fengsp** [comment]
@yupbank 

```
from rc import Cache
mycache = Cache()

@mycache.cache()
def x(a):
     return [a.encode('u8') for i in range(10)]
```

**Comment by yupbank** [comment]
i think this still would do pass my test_case.

with the my modified version of cache

assert x_return_first_time == x_return_first_second_time
